# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa7eb4cc7e6e2fccc7d430d3daba76a50a1e277e31cbf9229e9863d06d8dcd68ff17383a2652ca9bab80fdb2f0f4f08f45506ab3ac3fd525214bb8e9e353e96

test:
  secret_key_base: 2efe534fec56082f9d87a245769ef88c578a910d9d9f653d841eff2f7054acf9d7d42ef2fb71dcfc9569aa66edc69a54143f9228da425636bb2e1ea6ae8c65cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
